title: RennSport Engineering wiki
baseurl: /wiki

layouts_dir:  _picnic/_layouts
includes_dir: _picnic/_includes

# GitHub Pages
# None of these can actually be changed
safe: true
lsi: false
highlighter: rouge

# Formatting
markdown: kramdown
kramdown:
  input: GFM

# Permalinks
permalink: pretty
