title: RennSport Engineering wiki
baseurl: /wiki

# GitHub Pages
# None of these can actually be changed
safe: true
lsi: false
highlighter: rouge

# Formatting
markdown: kramdown
kramdown:
  input: GFM

# Permalinks
permalink: pretty
